#pragma once
#include "XLivePatchAPI.h"

// THIS IS AN AUTOGENERATED FILE
// DO NOT EDIT

#define BANG_NATIVE_SYM_ELEMENTS(TF_SIMPLE, TF_CUSTOM) \
	/* == BGadget == */ \
	{ "??0BGadget@@QAE@XZ", TF_CUSTOM<0xd26180, void, void*>(patchManager, X86Register::EDI, {X86Register::GENERIC_PARAM}, true) },\
	{ "?bLayoutObjUnkFunc4@BGadget@@UAEXXZ", TF_SIMPLE(0xd45460) },\
	{ "?bLayoutObjUnkFunc8@BGadget@@UAEXPAX@Z", TF_CUSTOM<0xd45460, void, void *>(patchManager, X86Register::EAX, {X86Register::EDI}, true) },\
	{ "?bLayoutObjUnkFuncC@BGadget@@UAEXHH@Z", TF_SIMPLE(0xdeadbe) },\
	{ "??2BGadget@@SAPAXI@Z", 0x767bd3 },\
	{ "??_UBGadget@@SAPAXI@Z", 0x76861d },\
	{ "??3BGadget@@SAXPAX@Z", 0x767b0d },\
	{ "??_VBGadget@@SAXPAX@Z", 0x767b0d },\
	{ "", 0x0 }

#define BANG_NATIVE_ALLOC_OVERRIDE \
	static void* operator new(unsigned int size); \
	static void* operator new[](unsigned int size); \
	static void operator delete(void* ptr); \
	static void operator delete[](void* ptr); 
