#pragma once
// THIS IS AN AUTOGENERATED FILE
// DO NOT EDIT

#define BANG_NATIVE_SYM_ELEMENTS(TF_SIMPLE, TF_CUSTOM) \
	/* == BCore == */ \
	{ "??1BCore@@UAE@XZ", TF_SIMPLE(0x6b498f) },\
	{ "?BCoreUnkFunc8@BCore@@UAEHXZ", TF_SIMPLE(0x202966) },\
	{ "?BCoreUnkFunc12@BCore@@UAEHXZ", TF_SIMPLE(0x63383c) },\
	{ "?BCoreUnkFunc16@BCore@@UAEHXZ", TF_SIMPLE(0x52442) },\
	{ "?BCoreUnkFunc20@BCore@@UAEHXZ", TF_SIMPLE(0x52442) },\
	{ "?BCoreUnkFunc24@BCore@@UAEHXZ", TF_SIMPLE(0x52442) },\
	{ "?BCoreUnkFunc28@BCore@@UAEHXZ", TF_SIMPLE(0x52442) },\
	{ "?BCoreUnkFunc32@BCore@@UAEOXZ", TF_SIMPLE(0x6b497d) },\
	{ "?BCoreUnkFunc36@BCore@@UAEHH@Z", TF_SIMPLE(0x6b4984) },\
	{ "?BCoreUnkFunc40@BCore@@UAEHHHH@Z", TF_SIMPLE(0xe2926) },\
	{ "?BCoreUnkFunc44@BCore@@UAEHHHH@Z", TF_SIMPLE(0xe2926) },\
	{ "?ShowMessageBox@BCore@@UAEHABVBString@@HPB_W@Z", TF_SIMPLE(0xe2926) },\
	{ "?BCoreUnkFunc52@BCore@@UAEHH@Z", TF_SIMPLE(0x1fde49) },\
	{ "?BCoreUnkFunc56@BCore@@UAEPAHH@Z", TF_SIMPLE(0x1f71) },\
	{ "?BCoreUnkFunc60@BCore@@UAEHXZ", TF_SIMPLE(0x482556) },\
	{ "?BCoreUnkFunc64@BCore@@UAEHXZ", TF_SIMPLE(0x52442) },\
	{ "?BCoreUnkFunc68@BCore@@UAEHXZ", TF_SIMPLE(0x52442) },\
	{ "?BCoreUnkFunc72@BCore@@UAEHXZ", TF_SIMPLE(0x52442) },\
	{ "?BCoreUnkFunc76@BCore@@UAEHE@Z", TF_SIMPLE(0x1f71) },\
	{ "?BCoreUnkFunc80@BCore@@UAEHXZ", TF_SIMPLE(0x474c9) },\
	{ "?BCoreUnkFunc84@BCore@@UAEHXZ", TF_SIMPLE(0x11e6) },\
	{ "?BCoreUnkFunc88@BCore@@UAEHXZ", TF_SIMPLE(0x11e6) },\
	{ "?BCoreUnkFunc92@BCore@@UAEHXZ", TF_SIMPLE(0x11e6) },\
	{ "?BCoreUnkFunc96@BCore@@UAEHXZ", TF_SIMPLE(0x18ea6b) },\
	{ "?BCoreUnkFunc100@BCore@@UAEHHHHH@Z", TF_SIMPLE(0x384a8e) },\
	{ "?BCoreUnkFunc104@BCore@@UAEHHHHHH@Z", TF_SIMPLE(0x1000) },\
	{ "?BCoreUnkFunc108@BCore@@UAEHHHHHHHH@Z", TF_SIMPLE(0x54e09f) },\
	{ "?BCoreUnkFunc112@BCore@@UAEHHHDE@Z", TF_SIMPLE(0x6b498a) },\
	{ "?BCoreUnkFunc116@BCore@@UAEHHE@Z", TF_SIMPLE(0x4e511) },\
	{ "?BCoreUnkFunc120@BCore@@UAE_NXZ", TF_SIMPLE(0x18ea6b) },\
	{ "?BCoreUnkFunc124@BCore@@UAEHXZ", TF_SIMPLE(0x18ea6b) },\
	{ "?BCoreUnkFunc128@BCore@@UAE_NXZ", TF_SIMPLE(0x18ea6b) },\
	{ "?BCoreUnkFunc132@BCore@@UAEHH@Z", TF_SIMPLE(0x1f71) },\
	{ "?BCoreUnkFunc136@BCore@@UAEHH@Z", TF_SIMPLE(0x202966) },\
	{ "?BCoreUnkFunc140@BCore@@UAEHHH@Z", TF_SIMPLE(0x4e511) },\
	{ "?BCoreUnkFunc144@BCore@@UAEHHH@Z", TF_SIMPLE(0x4e511) },\
	{ "??2BCore@@SAPAXI@Z", TF_SIMPLE(0x398) },\
	{ "??_UBCore@@SAPAXI@Z", TF_SIMPLE(0x398) },\
	{ "??3BCore@@SAXPAX@Z", TF_SIMPLE(0x548) },\
	{ "??_VBCore@@SAXPAX@Z", TF_SIMPLE(0x548) },\
	/* == BString == */ \
	{ "??0BString@@QAE@XZ", TF_SIMPLE(0x133f) },\
	{ "??0BString@@QAE@ABV0@@Z", TF_SIMPLE(0x43aa0) },\
	{ "??0BString@@QAE@PB_W@Z", TF_SIMPLE(0x1a12) },\
	{ "??1BString@@QAE@XZ", TF_SIMPLE(0xca) },\
	{ "??2BString@@SAPAXI@Z", TF_SIMPLE(0x398) },\
	{ "??_UBString@@SAPAXI@Z", TF_SIMPLE(0x398) },\
	{ "??3BString@@SAXPAX@Z", TF_SIMPLE(0x548) },\
	{ "??_VBString@@SAXPAX@Z", TF_SIMPLE(0x548) },\
	{ "", 0x0 }

