branches:
  only:
  - master
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- Win32
build_script:
- cmd: |-
    mkdir build
    cd build
    echo Installing to %cd%/../build-install/%CONFIGURATION%
    cmake .. -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX="%cd%/../build-install/%CONFIGURATION%"
    cmake --build .
artifacts:
  - path: build-install/%CONFIGURATION%/bin
    name: UHC
